### ISSUE TITLE
Rest api?

### ISSUE THREAD

**Issue by Daniel-dev22** [earlephilhower/aquaweb#11]
Hi, any plans for a rest API?

Does this project still work as well?

**Comment by earlephilhower** [comment]
No REST API planned.

Because this is essentially just a dumb TTY I'm not sure how it would be useful.  If we had direct commands to the head unit, instead of a menu we navigate, it works make much more sense.

**Comment by ballle98** [comment]
@Daniel-dev22  you may want to consider https://github.com/sfeakes/AqualinkD as an alternative.  It is designed to run as a stateful service.  it has a web UI, REST and MQTT interface.  It works well with Openhab and can be integrated with google and Alexa.  If you have a PDA only panel (no RS support) I have a fork with some PDA tweaks https://github.com/ballle98/AqualinkD

**Comment by Daniel-dev22** [comment]
> @Daniel-dev22  you may want to consider https://github.com/sfeakes/AqualinkD as an alternative.  It is designed to run as a stateful service.  it has a web UI, REST and MQTT interface.  It works well with Openhab and can be integrated with google and Alexa.  If you have a PDA only panel (no RS support) I have a fork with some PDA tweaks https://github.com/ballle98/AqualinkD

Somehow I missed that library in my search thank you for this.
